import { Inter } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils"

import {Sidebar} from '@/components/sidebar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TradeSee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body 
      style={{ background: "#181a20" }}
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.className
      )}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
